In [1]:
# Configuración del entorno
import os
import sys
sys.path.append(os.path.abspath('..'))  # Para importar desde src
import pandas as pd

In [2]:
# Carga de datos con pandas desde src
from src.carga_numpy import cargar_datos
ruta_archivo = '../data/retail_sales_dataset.csv'
df = pd.read_csv(ruta_archivo)
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [3]:
#Total de ventas por categoria
ventas_por_categoria = df.groupby("Product Category")["Total Amount"].sum().sort_values(ascending=False)
ventas_por_categoria

Product Category
Electronics    156905
Clothing       155580
Beauty         143515
Name: Total Amount, dtype: int64

In [4]:
#promedio de ventas diarias por categoria
df["Date"] = pd.to_datetime(df["Date"])
ventas_diarias = df.groupby(["Date", "Product Category"])["Total Amount"].sum().reset_index()
promedio_ventas_diarias = ventas_diarias.groupby("Product Category")["Total Amount"].mean().sort_values(ascending=False)
promedio_ventas_diarias

Product Category
Electronics    716.461187
Beauty         703.504902
Clothing       670.603448
Name: Total Amount, dtype: float64

In [ ]:
#categorias con la mayora y menor cantidad de ventas
categoria_mayor_venta = ventas_por_categoria.idxmax()
categoria_menor_venta = ventas_por_categoria.idxmin()
print("Categoría con mayor venta:", categoria_mayor_venta)
print("Categoría con menor venta:", categoria_menor_venta)

In [5]:
#filtro por categoria especifica
filtro_electronics = df[df['Product Category'] == 'Electronics']
filtro_electronics.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
12,13,2023-08-05,CUST013,Male,22,Electronics,3,500,1500
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000

In [6]:
#Estadisticas adicionales
# Suma total de ventas
total_ventas = df['Total Amount'].sum()
# Precio promedio por unidad
precio_promedio = df['Price per Unit'].mean()
# Cantidad total de productos vendidos
cantidad_total = df['Quantity'].sum()
total_ventas, precio_promedio, cantidad_total

(456000, 179.89, 2514)